import type { PlaceCategory } from "@pathy/shared";

export const CATEGORY_ICONS: Record<PlaceCategory, string> = {
  museum: "🏛️",
  castle: "🏰",
  church: "⛪",
  viewpoint: "🔭",
  nature: "🌿",
  park: "🌳",
  memorial: "🕯️",
  archaeology: "🏺",
  "street-art": "🎨",
  landmark: "📍",
  heritage: "🧶",
  engineering: "⚙️",
  ethnography: "🪵",
  trail: "🥾",
  beach: "🏖️",
  "water-activity": "🚣",
  adventure: "🎢",
  sports: "⚽",
  food: "🍽️",
  lodging: "🛏️",
  transport: "🚌",
  service: "ℹ️",
  shopping: "🛍️",
  event: "🎭",
  animal: "🐾",
  wellness: "💧",
  other: "✨",
};
